import React from 'react';
import type { Metadata } from 'next';
import { Breadcrumbs } from '@/components/seo/Breadcrumbs';
import { JsonLd } from '@/components/seo/JsonLd';

export const metadata: Metadata = {
  title: 'Terms of Service | Sellrivo',
  description:
    'Terms and conditions governing the use of Sellrivo web calculators and content.',
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      <Breadcrumbs items={[{ name: 'Terms of Service', href: '/terms' }]} />

      <JsonLd
        type="WebPage"
        data={{
          name: 'Terms of Service | Sellrivo',
          description: 'Terms of service and usage conditions.',
        }}
      />

      <div className="space-y-2">
        <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-slate-100">
          Terms of Service
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400">Effective Date: August 2026</p>
      </div>

      <div className="prose dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 text-sm sm:text-base space-y-4">
        <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100">1. Acceptance of Terms</h3>
        <p>
          By accessing and using Sellrivo, you agree to comply with and be bound by these Terms of Service.
        </p>

        <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100">2. Informational Purpose Only</h3>
        <p>
          Sellrivo provides calculation tools and educational content strictly for informational and estimation purposes. Calculations are based on generalized fee formulas and user-entered assumptions.
        </p>

        <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100">3. Financial & Tax Disclaimer</h3>
        <p>
          The content and results generated by Sellrivo do not constitute financial, legal, accounting, or tax advice. Users are responsible for verifying official marketplace fee schedules directly with Etsy, Amazon, or their respective service providers before committing to business decisions.
        </p>

        <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100">4. Limitation of Liability</h3>
        <p>
          Sellrivo and its operators shall not be held liable for any financial losses, pricing errors, lost profits, or business disruptions arising from the use of or reliance on our calculators.
        </p>
      </div>
    </div>
  );
}
