import React from 'react';
import type { Metadata } from 'next';
import { Breadcrumbs } from '@/components/seo/Breadcrumbs';

export const metadata: Metadata = {
  title: 'Terms of Service | SellerMargin',
  description: 'Terms and conditions governing the use of SellerMargin web calculators and content.',
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      <Breadcrumbs items={[{ name: 'Terms of Service', href: '/terms' }]} />

      <div className="space-y-3">
        <h1 className="text-3xl sm:text-5xl font-black text-slate-900 dark:text-slate-100 tracking-tight">
          Terms of Service
        </h1>
        <p className="text-xs text-slate-400">Last updated: August 1, 2026</p>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 sm:p-8 border border-slate-200 dark:border-slate-800 space-y-6 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
        <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">1. Informational Nature of Calculators</h2>
        <p>
          SellerMargin provides calculation tools and educational content strictly for informational and estimation purposes. Calculations are based on generalized fee formulas and user-entered assumptions.
        </p>

        <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">2. No Financial, Tax, or Legal Advice</h2>
        <p>
          The content and results generated by SellerMargin do not constitute financial, legal, accounting, or tax advice. Users are responsible for verifying official marketplace fee schedules directly with Etsy, Amazon, or their respective service providers before committing to business decisions.
        </p>

        <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">3. Limitation of Liability</h2>
        <p>
          SellerMargin and its operators shall not be held liable for any financial losses, pricing errors, lost profits, or business disruptions arising from the use of or reliance on our calculators.
        </p>
      </div>
    </div>
  );
}
